from django.db import models

class RespostaFormulario(models.Model):
    equipamento = models.CharField(max_length=100)
    qual_linha = models.CharField(max_length=100)
    extensao = models.CharField(max_length=100)
    extensao_sem_leitura = models.CharField(max_length=100,blank=True,null=True)
    espacamento_medio = models.CharField(max_length=100)
    tipo_dormente = models.CharField(max_length=100)
    quantidade_dormentes_intercalados = models.CharField(max_length=100,blank=True,null=True)
    tipo_fixacao = models.CharField(max_length=100)
    proporcao_fixacao_mista = models.CharField(max_length=100,blank=True,null=True)
    tdc = models.CharField(max_length=100, null=True)
    concreto = models.CharField(max_length=100)
    isolado_nao_isol = models.CharField(max_length=100)
    malha1 = models.CharField(max_length=100,blank=True,null=True)
    malha2 = models.CharField(max_length=100,blank=True,null=True)
    malha3 = models.CharField(max_length=100,blank=True,null=True)
    malha4 = models.CharField(max_length=100,blank=True,null=True)
    malha5 = models.CharField(max_length=100,blank=True,null=True)
    malha6 = models.CharField(max_length=100,blank=True,null=True)
    malha7 = models.CharField(max_length=100,blank=True,null=True)
    malha8 = models.CharField(max_length=100,blank=True,null=True)
    malha9 = models.CharField(max_length=100,blank=True,null=True)
    malha10 = models.CharField(max_length=100,blank=True,null=True)
    junta = models.IntegerField(default=0,blank=True,null=True)
    guarda = models.IntegerField(default=0,blank=True,null=True)
    solda = models.IntegerField(default=0,blank=True,null=True)
    Placa_Falta = models.IntegerField(default=0,blank=True,null=True)
    Placa_NOK = models.IntegerField(default=0,blank=True,null=True)
    Tirefond_Falta = models.IntegerField(default=0,blank=True,null=True)
    Tirefond_NOK = models.IntegerField(default=0,blank=True,null=True)
    Furo_NOK = models.IntegerField(default=0,blank=True,null=True)
    Shoulder_Falta = models.IntegerField(default=0,blank=True,null=True)
    Shoulder_NOK = models.IntegerField(default=0,blank=True,null=True)
    Palmilha_Falta = models.IntegerField(default=0,blank=True,null=True)
    Palmilha_NOK = models.IntegerField(default=0,blank=True,null=True)
    Isolador_Falta = models.IntegerField(default=0,blank=True,null=True)
    Isolador_NOK = models.IntegerField(default=0,blank=True,null=True)