# Generated by Django 4.2.3 on 2023-07-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaformulario',
            name='tdc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
